/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-07-01 19:16:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mtienda;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import soft.cise.modeloDTO.productoDTO;
import soft.cise.modeloDao.metProduc;
import soft.cise.controlador.comProducto;
import soft.cise.modeloDTO.articuloDTO;
import java.util.ArrayList;

public final class carrito_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/mtienda/../WEB-INF/jspfTienda/cfooter.jspf", Long.valueOf(1688234447402L));
    _jspx_dependants.put("/mtienda/../WEB-INF/jspfTienda/cStylos.jspf", Long.valueOf(1688234447401L));
    _jspx_dependants.put("/mtienda/../WEB-INF/jspfTienda/nav.jspf", Long.valueOf(1688234447407L));
    _jspx_dependants.put("/mtienda/../WEB-INF/jspfTienda/cJavaScrip.jspf", Long.valueOf(1688234447399L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("soft.cise.modeloDao.metProduc");
    _jspx_imports_classes.add("soft.cise.modeloDTO.articuloDTO");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("soft.cise.modeloDTO.productoDTO");
    _jspx_imports_classes.add("soft.cise.controlador.comProducto");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession sesion = request.getSession();
    ArrayList<articuloDTO> articulos = sesion.getAttribute("carrito") == null ? null : (ArrayList) sesion.getAttribute("carrito");


      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        ");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"  crossorigin=\"anonymous\">\n");
      out.write("<!--fontawesome-->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\"  crossorigin=\"anonymous\">\n");
      out.write("<link href=\"resource/css/tienda.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("<!--Letras-->\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css\"/>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.7.12/dist/sweetalert2.min.css\" integrity=\"sha256-7jUS+MWeqkFdmW9ozkZ7mPagz+QmMbsBlt+Q3MsE+FU=\" crossorigin=\"anonymous\">");
      out.write("\n");
      out.write("        <link href=\"resource/css/allproduct.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <title>ChiniMini Importaciones</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");

    HttpSession sessionOk = request.getSession();

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-white bg-white  fixed-top\" id=\"mainNav\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\"><img class=\"imagen-logo\" src=\"resource/img/tienda/logo.png\"></a>\n");
      out.write("        <button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            Menu\n");
      out.write("            <i class=\"fas fa-bars\"></i>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/comcatalogo.do?txtAccion=carrito\">Carrito");
//=contador 
      out.write("</a>\n");
      out.write("                </li>\n");
      out.write("                ");
 
                    if (sessionOk.getAttribute("perfil") == null) {
                
      out.write("\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"login.jsp\">Acceder</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"registrar.jsp\">Registrarse</a>\n");
      out.write("                </li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                ");

                    if (sessionOk.getAttribute("perfil") != null) {
                
      out.write("\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">");
      out.print(sessionOk.getAttribute("nombre") );
      out.write("</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/conusuario.do?txtAccion=cerrarSession\">Cerrar Session</a>\n");
      out.write("                </li>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"espacio\"></div>\n");
      out.write("        <section id=\"barraNavegacion\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"menuopciones\">\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"index.jsp\">Inicio</a></li>\n");
      out.write("                        <li><a href=\"#\">Mas Productos</a></li>\n");
      out.write("                        <li><a href=\"#\">Carrito</a></li>\n");
      out.write("                        <li style=\"float: right\"><input class=\"form-control\" id=\"myInput\" type=\"text\" placeholder=\"Search..\"></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <section>\n");
      out.write("            <div class=\"contenido\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"card cardoff\">\n");
      out.write("                        <div class=\"card-header\">\n");
      out.write("                            Productos seleccionados\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <table class=\"table table-bordered table-hover\">\n");
      out.write("                                <thead class=\"table-primary\" align=\"center\">\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>Imagen</th>\n");
      out.write("                                        <th>Nombre</th>\n");
      out.write("                                        <th>Cantidad</th>\n");
      out.write("                                        <th>Precio</th>\n");
      out.write("                                        <th>Total</th>\n");
      out.write("                                        <th>Opciones</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody>\n");
      out.write("                                    ");
  metProduc metp = new metProduc();
                                        double total = 0;
                                        double costoEnvio = 0;
                                        double IGV = 0;
                                        if (articulos != null) {
                                            for (articuloDTO a : articulos) {
                                                productoDTO producto = metp.sql_selectById(a.getIdProducto());
                                                total += a.getCantidad() * producto.getPrecioVenta();
                                                costoEnvio += total / 70;
                                                IGV += producto.getIGV();

                                    
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td><img src=\"comcatalogo.do?txtAccion=imagen&id=");
      out.print(a.getIdProducto());
      out.write("\" class=\"card-img-top\" style=\"width: 100px;\"/></td>\n");
      out.write("                                        <td>");
      out.print(producto.getNombProducto());
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print(a.getCantidad());
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print(producto.getPrecioVenta());
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print(Math.round(producto.getPrecioVenta() * a.getCantidad() * 100.0) / 100.0);
      out.write("</td>\n");
      out.write("                                        <td align=\"center\" >\n");
      out.write("                                            <span id=\"idArticulo\" style=\"display: none;\">");
      out.print(a.getIdProducto());
      out.write("</span>\n");
      out.write("                                            <span id=\"nombreArticulo\" style=\"display: none;\">");
      out.print(producto.getNombProducto());
      out.write("</span>\n");
      out.write("                                            <a class=\"btn btn-warning btn-sm\" type=\"submit\" href=\"\" id=\"deleteItem\"><i class=\"fa fa-times\"></i></a>\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    ");
}
                                        }
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"espacio\"></div>\n");
      out.write("\n");
      out.write("                    <a class=\"btn btn-warning\" href=\"javascript:window.history.go(-2)\">Seguir Comprando</a>\n");
      out.write("                    <div class=\"espacio\"></div>\n");
      out.write("                    <form class=\"needs-validation\" action=\"");
      out.print(request.getContextPath());
      out.write("/comcatalogo.do?txtAccion=Comprar\" method=\"POST\" novalidate>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <div class=\"card\">\n");
      out.write("                                    <div class=\"card-header\">\n");
      out.write("                                        Datos del Cliente\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"card-body\">\n");
      out.write("                                        ");
 metProduc metp1 = new metProduc();
                                            int productoCon = 0;
                                            if (articulos != null) {
                                                for (articuloDTO a : articulos) {
                                                    productoCon += 1;
                                        
      out.write("\n");
      out.write("                                        <div class=\"form-row\">\n");
      out.write("                                            <div class=\"col-md-6 mb-3\">\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" name=\"txtId");
      out.print(productoCon);
      out.write("\" value=\"");
      out.print(a.getIdProducto());
      out.write("\" readonly=\"readonly\">\n");
      out.write("                                            </div>\n");
      out.write("                                                <input type=\"hidden\" name=\"txtCantidad");
      out.print(productoCon);
      out.write("\" value=\"");
      out.print(a.getCantidad());
      out.write("\">\n");
      out.write("\n");
      out.write("                                        ");
 }
                                            }
      out.write("\n");
      out.write("                                            <div class=\"col-md-6 mb-3\">\n");
      out.write("                                                <input class=\"form-control\" type=\"text\" name=\"idUsuario\" value=\"");
      out.print(session.getAttribute("idUsuario") );
      out.write("\" readonly=\"readonly\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                            <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Nombre Completo</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtNombreCliente\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su nombre completo.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>DNI</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtDni\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su DNI.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Telefono 1</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtTelefono1\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su telefono.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Telefono 2</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtTelefono2\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su telefono.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Departamento</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtDepartamento\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su departamento.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Provincia</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtProvincia\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su provincia.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Distrito</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtDistrito\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su Distrito.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <div class=\"row\">\n");
      out.write("                                                <div class=\"col-4\">\n");
      out.write("                                                    <label>Direccion</label>\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"col-md-8\">\n");
      out.write("                                                    <input class=\"form-control\" type=\"text\" name=\"txtDireccion\" required>\n");
      out.write("                                                    <div class=\"invalid-feedback\">\n");
      out.write("                                                    Por favor, ingrese su Direccion.\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>    \n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <br>\n");
      out.write("                                            <spam style=\"border-bottom: 1px solid #000;\">Datos de la compra</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <spam>Total producto</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-8\">\n");
      out.write("                                            <input class=\"form-control\" id=\"txtSubtotal\" name=\"txtTotalProducto\" value=\"");
      out.print(Math.round(total * 100.0) / 100.0);
      out.write("\" type=\"text\" readonly=\"readonly\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <spam>Costo de Envio</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-8\">\n");
      out.write("                                            <input class=\"form-control\" id=\"txtSubtotal2\" name=\"txtCostoEnvio\" type=\"text\" value=\"");
      out.print(Math.round(costoEnvio * 100.0) / 100.0);
      out.write("\" readonly=\"readonly\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-8\">\n");
      out.write("                                            <input class=\"form-control\" name=\"txtIGV\" type=\"hidden\" value=\"");
      out.print(Math.round(IGV * 100.0) / 100.0);
      out.write("\" readonly=\"readonly\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </div> \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <spam>Total a pagar</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-8\">\n");
      out.write("                                            <input class=\"form-control\" name=\"txtTotalPago\" type=\"text\" value=\"");
      out.print(Math.round((total + costoEnvio) * 100.0) / 100.0);
      out.write("\" readonly=\"readonly\" >\n");
      out.write("                                        </div>\n");
      out.write("                                    </div> \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <br>\n");
      out.write("                                            <spam style=\"border-bottom: 1px solid #000;\">Pago</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-4\">\n");
      out.write("                                            <spam>Paga con</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-8\">\n");
      out.write("                                            <div class=\"menuPago\">\n");
      out.write("                                                <ul>\n");
      out.write("                                                    <li><input type=\"radio\" name=\"txtMedioPago\" value=\"mastercard\"><i class=\"fab fa-cc-mastercard\"></i></li>\n");
      out.write("                                                    <li><input type=\"radio\" name=\"txtMedioPago\" value=\"paypal\"><i class=\"fab fa-cc-paypal\"></i></li>\n");
      out.write("                                                    <li><input type=\"radio\" name=\"txtMedioPago\" value=\"visa\"><i class=\"fab fa-cc-visa\"></i></li>\n");
      out.write("                                                </ul>\n");
      out.write("                                            </div>      \n");
      out.write("                                        </div>\n");
      out.write("                                    </div> \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"form-group\">\n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-4\">\n");
      out.write("                                            <spam>Cuenta</spam>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-8\">\n");
      out.write("                                            <input class=\"form-control\" name=\"txtCuenta\" type=\"text\" required>\n");
      out.write("                                            <div class=\"invalid-feedback\">\n");
      out.write("                                            Por favor, ingrese su cuenta.\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div> \n");
      out.write("                                </div>\n");
      out.write("                                <input type=\"submit\" id=\"btn_pagar\" class=\"btn btn-primary btn-block\" value=\"Comprar\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                                    <script>\n");
      out.write("                                    // Example starter JavaScript for disabling form submissions if there are invalid fields\n");
      out.write("                                    (function() {\n");
      out.write("                                      'use strict';\n");
      out.write("                                      window.addEventListener('load', function() {\n");
      out.write("                                        // Fetch all the forms we want to apply custom Bootstrap validation styles to\n");
      out.write("                                        var forms = document.getElementsByClassName('needs-validation');\n");
      out.write("                                        // Loop over them and prevent submission\n");
      out.write("                                        var validation = Array.prototype.filter.call(forms, function(form) {\n");
      out.write("                                          form.addEventListener('submit', function(event) {\n");
      out.write("                                            if (form.checkValidity() === false) {\n");
      out.write("                                              event.preventDefault();\n");
      out.write("                                              event.stopPropagation();\n");
      out.write("                                              \n");
      out.write("                                            }\n");
      out.write("                                            form.classList.add('was-validated');\n");
      out.write("                                            \n");
      out.write("                                          }, false);\n");
      out.write("                                        });\n");
      out.write("                                      }, false);\n");
      out.write("                                      \n");
      out.write("                                    })();\n");
      out.write("                                    </script>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        ");
      out.write("<footer>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <span class=\"copyright\">Copyright &copy; ChiniMini-Importaciones 2023</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\" align=\"center\">\n");
      out.write("                <ul class=\"social-buttons\">\n");
      out.write("                    <li class=\"list-inline-item\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"fab fa-twitter\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"list-inline-item\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"list-inline-item\">\n");
      out.write("                        <a href=\"#\">\n");
      out.write("                            <i class=\"fab fa-linkedin-in\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-4\">\n");
      out.write("                <ul class=\"list-inline quicklinks\">\n");
      out.write("                    <li class=\"list-inline-item\">\n");
      out.write("                        <a href=\"#\">Politicas de Privacidad</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"list-inline-item\">\n");
      out.write("                        <a href=\"#\">Terminos de Uso</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--JavasScrip-Jquery-Bootstrap-->\n");
      out.write("        ");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"  crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"  crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"  crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"resource/js/tienda.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"resource/js/jquery.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"resource/js/carrito.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js\"></script>\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/alertify.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.7.12/dist/sweetalert2.all.min.js\" integrity=\"sha256-2Dbg51yxfa7qZ8CSKqsNxHtph8UHdgbzxXF9ANtyJHo=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"resource/js/alert.js\" type=\"text/javascript\"></script>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
